#pragma once

#define SECOND_TO_SECOND 1
#define MINUTE_TO_SECOND(X) (60 * SECOND_TO_SECOND * X)
#define HOUR_TO_SECOND(X) (60 * MINUTE_TO_SECOND(X))
#define DAY_TO_SECOND(X) (24 * HOUR_TO_SECOND(X))

#define SECOND_TO_MILLISECOND(X) (1000 * X)
#define MINUTE_TO_MILLISECOND(X) (60 * SECOND_TO_MILLISECOND(X))
#define HOUR_TO_MILLISECOND(X) (60 * MINUTE_TO_MILLISECOND(X))
#define DAY_TO_MILLISECOND(X) (24 * HOUR_TO_MILLISECOND(X))

#define COIN(X) (100000000L * X)
